config/routes.rb
Rails.application.routes.draw do

  devise_for :admins

  resources :educations, except: [:show]
  resources :portfolios, except: [:show]
  resources :skills, except: [:show]
  resources :technologies, except: [:show]
  resources :work_experiences, except: [:show]

  get 'static_pages/home'
  match '/contact', to: 'static_pages#contact', via: 'get'

  root to: "static_pages#home"

end

app/models/portfolio.rb
class Portfolio < ActiveRecord::Base
   has_attached_file :image, :styles => { :medium => "500x500", :thumb => "300x300>" }
   validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/

end

app/controllers/portfolios_controller.rb
class PortfoliosController < ApplicationController
  before_action :set_portfolio, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_admin!, only: [:new, :create, :update, :edit, :destroy]


  # GET /portfolios
  # GET /portfolios.json
  def index
    @portfolios = Portfolio.all.order('created_at DESC')
    @technologies = Technology.all
  end

  # GET /portfolios/1
  # GET /portfolios/1.json
  def show
  end

  # GET /portfolios/new
  def new
    @portfolio = Portfolio.new
  end

  # GET /portfolios/1/edit
  def edit
  end

  # POST /portfolios
  # POST /portfolios.json
  def create
    @portfolio = Portfolio.new(portfolio_params)

    respond_to do |format|
      if @portfolio.save
        format.html { redirect_to @portfolio, notice: 'Portfolio was successfully created.' }
        format.json { render :show, status: :created, location: @portfolio }
      else
        format.html { render :new }
        format.json { render json: @portfolio.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /portfolios/1
  # PATCH/PUT /portfolios/1.json
  def update
    respond_to do |format|
      if @portfolio.update(portfolio_params)
        format.html { redirect_to @portfolio, notice: 'Portfolio was successfully updated.' }
        format.json { render :show, status: :ok, location: @portfolio }
      else
        format.html { render :edit }
        format.json { render json: @portfolio.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /portfolios/1
  # DELETE /portfolios/1.json
  def destroy
    @portfolio.destroy
    respond_to do |format|
      format.html { redirect_to portfolios_url, notice: 'Portfolio was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_portfolio
      @portfolio = Portfolio.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def portfolio_params
      params.require(:portfolio).permit(:name, :description, :image)
    end
end

app/helpers/portfolios_helper.rb
module PortfoliosHelper
end

app/views/portfolios/_form.html.erb
<%= form_for(@portfolio) do |f| %>
  <% if @portfolio.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@portfolio.errors.count, "error") %> prohibited this portfolio from being saved:</h2>

      <ul>
      <% @portfolio.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :description %>
    <%= f.text_area :description, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label "Sites URL" %>
    <%= f.text_field :site_url %>
  </div>
  <div class="form-group">
    <%= f.label :image %>
    <%= f.file_field :image, class: "form-control" %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/portfolios/edit.html.erb
<h1>Editing Portfolio</h1>

<%= render 'form' %>

<%= link_to 'Show', @portfolio %> |
<%= link_to 'Back', portfolios_path %>

app/views/portfolios/index.html.erb
<% if admin_signed_in? %>
<%= link_to "Add project", new_portfolio_path %>
<% end %>

<div class="row">
    <div class="col-md-8 col-md-offset-2 text-center">
        <h1 class="cursive">Take a look at some of my projects!</h1>
        <p>Here are few of my projects I have done from the beginning of my web development times till now.  All APPS were built on Ruby on Rails including this site!  Most of the gems used in these apps consisted of devise and bootstrap-sass.  Some apps used API's for their features. The company websites listed below were all html, CSS, JS built with no frameworks in place.</p>
    </div>
</div>

<hr>
<div class="col-md-9">
    <% @portfolios.each do |portfolio| %>
    <div class="col-md-12 card">
        <div class="col-md-12">
            <h3><%= portfolio.name.titleize %></h3>
            <div class="col-md-6">
                <%= image_tag portfolio.image.url, class: "img-responsive project", alt: "Project image from #{portfolio.name}" %>
            </div>
            <div class="col-md-6" id="port-desc">
                <p><%= portfolio.description %></p>
                <% if current_admin %>
                <%= link_to "Edit", edit_portfolio_path(portfolio) %> <br/>
                <%= link_to "Delete", portfolio, method: :delete, data: { confirm: "Are you sure?" } %>
                <% end %>
            </div>
        </div>
    </div>
    <% end %>
</div>

<div class="col-md-3 experience">
    <h3 class="text-center cursive"><u>Technology</u></h3>
    <% @technologies.each do |tech| %>
    <ul>
        <li><b><%= tech.name %></b></li>
    </ul>
    <% end %>
</div>

app/views/portfolios/new.html.erb
<div class="col-md-6 col-md-offset-3">

<div class="panel panel-default">
    <div class="panel-heading">
        <h3 class="panel-title">Add new piece of work</h3>
    </div>

    <div class="panel-body">
        <%= render 'form' %>
    </div>
</div>


<%= link_to 'Back', portfolios_path %>
</div>

app/views/portfolios/show.html.erb
<p id="notice"><%= notice %></p>

<div class="col-md-12">
   <div class="col-md-8">
      <%= image_tag @portfolio.image.url, class: "img-responsive image-show" %>
   </div>
   <div class="col-md-4">
      <div class="col-md-12 heading">
         <h4><%= @portfolio.name.titleize %></h4>
      </div>
      <div class="col-md-12 description">
         <p><%= @portfolio.description %></p>
      </div>
   </div>

   <%= link_to "Check out the website" %>
</div>