config/routes.rb
Rails.application.routes.draw do

  devise_for :admins

  resources :educations, except: [:show]
  resources :portfolios, except: [:show]
  resources :skills, except: [:show]
  resources :technologies, except: [:show]
  resources :work_experiences, except: [:show]

  get 'static_pages/home'
  match '/contact', to: 'static_pages#contact', via: 'get'

  root to: "static_pages#home"

end

app/models/work_experience.rb
class WorkExperience < ActiveRecord::Base
end

app/controllers/work_experiences_controller.rb
class WorkExperiencesController < ApplicationController
  before_action :set_work_experience, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_admin!, only: [:new, :create, :update, :edit, :destroy]

  # GET /work_experiences
  # GET /work_experiences.json
  def index
    @work_experiences = WorkExperience.all
    @work_experiences = @work_experiences.order(current_job: :desc)
  end

  # GET /work_experiences/1
  # GET /work_experiences/1.json
  def show
  end

  # GET /work_experiences/new
  def new
    @work_experience = WorkExperience.new
  end

  # GET /work_experiences/1/edit
  def edit
  end

  # POST /work_experiences
  # POST /work_experiences.json
  def create
    @work_experience = WorkExperience.new(work_experience_params)

    respond_to do |format|
      if @work_experience.save
        format.html { redirect_to work_experiences_path, notice: 'Work experience was successfully created.' }
        format.json { render :show, status: :created, location: @work_experience }
      else
        format.html { render :new }
        format.json { render json: @work_experience.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /work_experiences/1
  # PATCH/PUT /work_experiences/1.json
  def update
    respond_to do |format|
      if @work_experience.update(work_experience_params)
        format.html { redirect_to work_experiences_path, notice: 'Work experience was successfully updated.' }
        format.json { render :show, status: :ok, location: @work_experience }
      else
        format.html { render :edit }
        format.json { render json: @work_experience.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /work_experiences/1
  # DELETE /work_experiences/1.json
  def destroy
    @work_experience.destroy
    respond_to do |format|
      format.html { redirect_to work_experiences_url, notice: 'Work experience was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_work_experience
      @work_experience = WorkExperience.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def work_experience_params
      params.require(:work_experience).permit(:name, :start_date, :current_job, :end_date, :job_title, :description)
    end
  end

app/helpers/work_experiences_helper.rb
module WorkExperiencesHelper
   @colors = ["purple", "red", "orange", "peach", "yellow", "green"]
   # def card_color
   #    @colors = ["purple", "red", "orange", "peach", "yellow", "green"]
   #    @colors.each do |c|
   #       case c
   #       when "purple"
   #          "purple"
   #       when "red"
   #          "red"
   #       when "orange"
   #          "orange"
   #       when "peach"
   #          "peach"
   #       when "yellow"
   #          "yellow"
   #       when "green"
   #          "green"
   #       end
   #    end
   # end
end

app/views/work_experiences/_form.html.erb
<%= form_for(@work_experience) do |f| %>
  <% if @work_experience.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@work_experience.errors.count, "error") %> prohibited this work_experience from being saved:</h2>

      <ul>
      <% @work_experience.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<div class="col-md-6 col-md-offset-3">
  <div class="panel">

    <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :start_date %>
    <%= f.date_select :start_date, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :present? %>
    <%= f.check_box :current_job %>
  </div>
  <div class="form-group">
    <%= f.label :end_date %>
    <%= f.date_select :end_date, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :job_title %>
    <%= f.text_field :job_title, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :description %>
    <%= f.text_area :description, class: "form-control" %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>
  </div>
</div>

app/views/work_experiences/edit.html.erb
<h1>Editing Work Experience</h1>

<%= render 'form' %>

<%= link_to 'Show', @work_experience %> |
<%= link_to 'Back', work_experiences_path %>

app/views/work_experiences/index.html.erb
<% if admin_signed_in? %>
<%= link_to 'New Work experience', new_work_experience_path %>
<% end %>
<div class="row bg">
  <div class="col-md-12">
  <p>A scope of work experience</p>
  <div class="bg-img pull-left"></div>
  <div class="bg-img pull-left"></div>
  <div class="bg-img pull-left"></div>

    <!-- <div class="col-md-8 col-md-offset-2 text-center bg-content">
      <h1>A brief history of my work experiences</h1>
      <p>I'm a super curious individual and I have been grateful to be able to take something from every experience.  Having been in various work settings it's been awesome to bring on and enhance my abilities from <b><em>communication</em></b> skills and <b><em>team work</em></b> to <b><em>motivating</em></b>, setting, and then <b><em>implementing goals</em></b> all the way to <b><em>marketing</em></b> and <b><em>selling</em></b> products and services.  Now I'm in persuit of building super cool <b><em>solutions</em></b> through technology that solve real problems!</p>
    </div> -->
  </div>
</div>

<div class="row">
  <div class="col-md-12">
    <% @work_experiences.each do |job| %>
    <div class="row tan-bg p-card">
    <% if admin_signed_in?%>
    <%= link_to "edit", edit_work_experience_path(job) %>
    <% end %>
      <h3 class="job-name"><%= job.name %></h3>
      <h5 class="job-title"><i><%= job.job_title %></i></h5>
      <small>
        <%= job.start_date.strftime("%B %Y") %> -
        <% if job.current_job? %>
        Present
        <% else %>
        <%= job.end_date.strftime("%B %Y") %>
        <% end %>
      </small>
      <p class="job-desc"><%= job.description %></p>
    </div>
    <% end %>
  </div>
</div>

app/views/work_experiences/new.html.erb
<div class="panel panel-default">
    <div class="panel-heading">
        <h3 class="panel-title">Add Work Experience</h3>
    </div>
    <div class="panel-body">
        <%= render 'form' %>
    </div>
</div>


<%= link_to 'Back', work_experiences_path %>

app/views/work_experiences/show.html.erb
<p id="notice"><%= notice %></p>
<ul>
  <li><strong>Name:</strong> <%= @work_experience.name %></li>
  <li><strong>Start Date:</strong> <%= @work_experience.start_date %> -
    <% if @work_experience.current_job? %>
    Present
    <% else %>
    <%= @work_experience.end_date %>
  <% end %>
  </li>
  <li><strong>Job title:</strong> <%= @work_experience.job_title %></li>
  <li><strong>Description:</strong> <%= @work_experience.description %></li>
</ul>