config/routes.rb
Rails.application.routes.draw do

  devise_for :admins

  resources :educations, except: [:show]
  resources :portfolios, except: [:show]
  resources :skills, except: [:show]
  resources :technologies, except: [:show]
  resources :work_experiences, except: [:show]

  get 'static_pages/home'
  match '/contact', to: 'static_pages#contact', via: 'get'

  root to: "static_pages#home"

end

app/models/education.rb
class Education < ActiveRecord::Base

   def set_icon
      case school_name
      when "The Starter League"
         "code"
      when "Elgin Community College"
         "book"
      when "ACE Fitness"
         "bolt"
      end
   end

end

app/controllers/educations_controller.rb
require 'open-uri'
require 'json'

class EducationsController < ApplicationController
  before_action :set_education, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_admin!, only: [:new, :create, :update, :edit, :destroy]

  # GET /educations
  # GET /educations.json
  def index
    @icons = ["code", "anchor", "adjust"]
    @educations = Education.all

    cs_url = "https://www.codeschool.com/users/1733393.json"
    open_url = open(cs_url).read
    json_data = JSON.parse(open_url)
    @cs_badges = json_data['courses']['completed']
    @cs_info = json_data['user']

    tth_url = "https://teamtreehouse.com/traviseubanks.json"
    open_url = open(tth_url).read
    json_data = JSON.parse(open_url)
    @tth_badges = json_data['badges']
    @tth_points = json_data['points']
    @tth_courses = @tth_badges[5]
  end

  # GET /educations/1
  # GET /educations/1.json
  def show
  end

  # GET /educations/new
  def new
    @education = Education.new
  end

  # GET /educations/1/edit
  def edit
  end

  # POST /educations
  # POST /educations.json
  def create
    @education = Education.new(education_params)

    respond_to do |format|
      if @education.save
        format.html { redirect_to @education, notice: 'Education was successfully created.' }
        format.json { render :show, status: :created, location: @education }
      else
        format.html { render :new }
        format.json { render json: @education.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /educations/1
  # PATCH/PUT /educations/1.json
  def update
    respond_to do |format|
      if @education.update(education_params)
        format.html { redirect_to @education, notice: 'Education was successfully updated.' }
        format.json { render :show, status: :ok, location: @education }
      else
        format.html { render :edit }
        format.json { render json: @education.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /educations/1
  # DELETE /educations/1.json
  def destroy
    @education.destroy
    respond_to do |format|
      format.html { redirect_to educations_url, notice: 'Education was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_education
      @education = Education.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def education_params
      params.require(:education).permit(:school_name, :course_program, :description, :duration, :location)
    end
end

app/helpers/educations_helper.rb
module EducationsHelper

   def blue_if_even
    @length = @facts.length

   end
end

app/views/educations/_form.html.erb
   <%= simple_form_for(@education, html: { class: 'form-horizontal'}) do |f| %>
   <%= f.error_notification %>
   <%= f.input :school_name %>
   <%= f.input :course_program %>
   <%= f.input :location %>
   <%= f.input :duration %>
   <%= f.input :description %>
   <%= f.button :submit %>
   <% end %>

   <%= link_to 'Back', educations_path, class: "pull-right" %>

app/views/educations/edit.html.erb
<h1>Editing Education</h1>

<%= render 'form' %>

<%= link_to 'Show', @education %> |
<%= link_to 'Back', educations_path %>

app/views/educations/index.html.erb
<div class="row">
  <div class="col-md-12">
    <h1 class="edu-title">Education</h1>
    <div class="col-md-8">
      <% @educations.each do |education| %>
      <div class="well">
        <h4 class="text-center white-heading"> <%= education.school_name %></h4>
        <%= fa_icon "map-marker" %> <%= education.location%><br/>
        <%= fa_icon "bookmark-o" %> <span class="edu-basics"><%= education.course_program %></span><br/>
        <%= fa_icon "calendar"%> <%= education.duration %><br/>
        <p class="edu-desc"><%= education.description %></p>
        <% if admin_signed_in? %>
        <%= link_to 'Show', education %> |
        <%= link_to 'Edit', edit_education_path(education) %> |
        <%= link_to 'Delet', education, method: :delete, data: {confirm: 'Are you sure?'} %> |
        <% end %>
      </div>
      <% end %>
    </div>

    <div class="col-md-4 panel panel-default blue-panel">
      <div class="col-md-12 white-heading">
        <h4><%= fa_icon 'share-alt' %> TeamTreeHouse</h4>
        <%= link_to "TeamTreeHouse.com", "https://www.teamtreehouse.com" %>
      </div>

      <% @tth_points.each do |pt| %>
      <div class="col-md-6 panel-body">
        <!-- <div class="col-md-3 name-pts"> -->
        <h6><u><%= (pt[0]).upcase %></u></h6>
        <p class="pts"><%= number_with_delimiter pt[1] %> pts</p>
        <!-- </div> -->
      </div>
      <% end %>

    </div>
  </div>
</div>

<div class="spacer"></div>

<div class="row">
  <div class="blue-panel cs-panel">
    <div class="col-md-12 white-heading">
      <h3><%= fa_icon 'code' %> CodeSchool</h3>
      <%= link_to "CodeSchool.com", "https://www.codeschool.com", class:'pull-left' %>
      <div class="pull-right">(Total score: <%= number_with_delimiter @cs_info['total_score'] %>)</div>
    </div>
    <hr>

    <div class="row">
      <div class="col-md-12">
        <% @cs_badges.each do |badge| %>
        <div class="col-md-3">
          <%= image_tag badge['badge'], size: '35' %><br/>
          <%= badge['title'] %>
        </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/educations/new.html.erb
<div class="col-md-6 col-md-offset-3">
   <h1>New Education</h1>
   <%= render 'form' %>
</div>

app/views/educations/show.html.erb
<div class="row">
   <ul>
      <li><%= @education.school_name %></li>
      <li><%= @education.course_program %></li>
      <li><%= @education.location %></li>
      <li><%= @education.duration %></li>
      <li><%= @education.description %></li>
   </ul>
</div>