config/routes.rb
Rails.application.routes.draw do

  devise_for :admins

  resources :educations, except: [:show]
  resources :portfolios, except: [:show]
  resources :skills, except: [:show]
  resources :technologies, except: [:show]
  resources :work_experiences, except: [:show]

  get 'static_pages/home'
  match '/contact', to: 'static_pages#contact', via: 'get'

  root to: "static_pages#home"

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Travis Eubanks</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>

  <link href='https://fonts.googleapis.com/css?family=Merriweather' rel='stylesheet' type='text/css'>
  <link href='https://fonts.googleapis.com/css?family=Lato' rel='stylesheet' type='text/css'>
  <link href='https://fonts.googleapis.com/css?family=Damion' rel='stylesheet' type='text/css'>
</head>
<body>
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-71917595-1', 'auto');
  ga('send', 'pageview');

</script>
  <nav class="navbar navbar-default">
    <div class="container-fluid">
      <!-- Brand and toggle get grouped for better mobile display -->
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <%= link_to "Home", root_path, class: "navbar-brand" %>
      </div>

      <!-- Collect the nav links, forms, and other content for toggling -->
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">

        <ul class="nav navbar-nav navbar-right">
          <% if admin_signed_in? %>
          <li><%= link_to "Sign out", destroy_admin_session_path, :method => :delete %></li>
          <% end %>
          <li><%= link_to "Github", "https://github.com/eubanksanator" %></li>
          <li><%= link_to "Work Experience", work_experiences_path %></li>
          <li><%= link_to "Education", educations_path, data: {disable_with: "<i class='fa fa-spinner fa-spin'></i> Loading credentials..."} %></li>
          <li><%= link_to "Portfolio", portfolios_path %></li>
          <!-- <li><%# link_to "Skills", skills_path %></li> -->
          <!-- <li><%# link_to "Technologies", technologies_path %></li> -->
          <li><%= link_to "Contact", contact_path %></li>
        </ul>
      </div><!-- /.navbar-collapse -->
    </div><!-- /.container-fluid -->
  </nav>
  <div class="container">
    <p id="notice"><%= notice %></p>

    <%= yield %>
  </div>

</body>
</html>